### ISSUE TITLE
General Improvements

### ISSUE THREAD

**Issue by ajaypatelaj** [themeselection/vue-cheatsheet#1]
### Cheatsheet
- [x] Refer below cheatsheet, and consider adding helpful points
https://github.com/dekadentno/vue-cheat-sheet
https://dev.to/adnanbabakan/vue-cheat-sheet-1-194a
https://devhints.io/vue
https://learnvue.co/LearnVue-Vue-3-Cheatsheet.pdf
https://www.vuemastery.com/vue-cheat-sheet/

### Layout
- [x] The home page should look attractive with a Navbar and Footer 
- [x] Ask the Design team to create a Logo and other branding or promotional assets
- [x] Setup Navbar links: Suggestions (Blog, Freebies, Resources DD (Free Vuejs Admin Templates, Bootstrap Cheatsheet) link in header or footer)
- [x] Setup Footer and add helpful links (Add a link to theme selection)

Refer below cheatsheet links for inspiration of UI (Home, Navbar, Footer)
https://www.pythoncheatsheet.org/contributing
https://bootstrap-cheatsheet.themeselection.com/index.html
https://flowbite.com/tools/tailwind-cheat-sheet/

### Deployment
- [x] ~Vercel with subdomain: vue-cheatsheet.themeselection.com (https://bootstrap-cheatsheet.themeselection.com/)~ We now uses DO

**Comment by jd-solanki** [comment]
Cheatsheet released 🥳
