### ISSUE TITLE
😶‍🌫️ Replace custom component with CSS when VitePress wrap title in span tag

### ISSUE THREAD

**Issue by jd-solanki** [themeselection/vue-cheatsheet#3]
PR: https://github.com/vuejs/vitepress/pull/3522

---

Once above PR is resolved:

- [ ] Enable commented CSS in `content/.vitepress/theme/custom.scss` that has PR comment
- [ ] Remove `siteTitle: false,` from `config.mts`

I guess above two task will allow us to hide site title on home page only.

**Comment by UsmanLiaqat404** [comment]
PR created: https://github.com/themeselection/vue-cheatsheet/pull/6
